language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libopenmpi-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  # OSX Setup
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install open-mpi                                                                     ;fi

install:
  - export OMPI_MPICXX=$CXX
  - export OMPI_CXX=$CXX
  - export OMPI_MPICC=$CC
  - export OMPI_CC=$CC


script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install
